#!/usr/bin/env bash
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
netstat -tuln | awk '$6 == "LISTEN" { printf "%-5s %-7s %-7s %-23s %-23s %-11s %-s\n", $1, $2, $3, $4, $5, $6, $7 }'
