#!/usr/bin/env bash
# List all processes with detailed information

echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"
ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command

