#!/usr/bin/env bash
# display to infinity and beyond indefinitely with a 2 sec delay
# display I am invincible when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' 15
while true; do
	echo "to infinity and beyond"
	sleep 2
done
