#!/usr/bin/env bash
# this script displays the string "best school" 10 times using while loop and says hi on the 9th iteration

string="Best School"

counter=1
while [ $counter -le 10 ]
do
	echo "$string"
	((counter++))
	if [ $counter == 9 ]
	then
		echo "Hi"
	fi
done
