#!/usr/bin/env bash
# loop from 1 to 10 and display a string accordingly
str1="Best School"
str2="good luck"
str3="bad luck"
counter=1
while [ $counter -le 10 ]
do
	if [ $counter == 4 ]
	then
		echo "$str3"
	elif [ $counter == 8 ]
	then
		echo "$str2"
	else
		echo "$str1"
	fi
	((counter++))
done
