#!/usr/bin/env bash
# loop from 1 to 20 and display a string accordingly
# 4 => bad luck from china
# 9 => bad luck from Japan
# 17 => bad luck from Italy
# otherwise => the iteration number

counter=1
while [ $counter -le 20 ]
do
	case $counter in
		4)
			echo "$counter"
			echo "bad luck from China"
			;;
		9)
			echo "$counter"
			echo "bad luck from Japan"
			;;
		17)
			echo "$counter"
			echo "bad luck from Italy"
			;;
		*)
			echo "$counter"
			;;
	esac
	((counter++))
done
